---
title: 'TCC'
author: "Gustavo Theil"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggsankey)
library(ggnewscale)

library(sf)
library(mapview)
library(units)

library(rdrobust)
library(rddensity)
library(fixest)

mapviewOptions(basemaps = "CartoDB.Positron")
setwd("C:/git/TCC")
```

# Import dados

```{r "dados/eixos", cache = TRUE}
eixos <- read_sf("dados/PDE/sirgas_PDE_3-Eixos-EETU.shp") |>
  st_set_crs("epsg:31983") |> 
  select(geometry)

eixos.buffersimples <- eixos |> 
  st_buffer(1000) |> 
  st_union() |> 
  st_simplify(dTolerance = 100)

eixos.miolo <- eixos |> 
  st_buffer(50) |> 
  st_union() |> 
  st_buffer(-50) |> 
  nngeo::st_remove_holes() |> 
  st_as_sf()

eixos.contorno <- eixos |> 
  st_buffer(50) |> 
  st_union() |> 
  st_buffer(-50) |> 
  nngeo::st_remove_holes() |> 
  st_cast("MULTILINESTRING") |> 
  st_as_sf()

# Mapa eixo, geradores de eixo
list(
  eixos = bind_rows(eixos.miolo,
                    read_sf("dados/PDE/sirgas_PDE_3-Eixos-EETU.shp") |>
                      st_set_crs("epsg:31983") |> select(x = geometry), 
                    eixos.contorno),
  geradores_eixo = bind_rows(
    read_sf("dados/geradores-eixo/corredor-onibus/SIRGAS_SHP_corredoronibus_line.shp") |> 
      mutate(tipo = "onibus") |> select(tipo, geometry) |> st_set_crs("epsg:31983"),
    read_sf("dados/geradores-eixo/estacao-metro/SIRGAS_SHP_estacaometro_point.shp") |> 
      mutate(tipo = "metro") |> select(tipo, geometry) |> st_set_crs("epsg:31983"),
    read_sf("dados/geradores-eixo/estacao-trem/SIRGAS_SHP_estacaotrem.shp") |> 
      mutate(tipo = "trem") |> select(tipo, geometry) |> st_set_crs("epsg:31983")),
  macroareas = read_sf("dados/macroareas/SIRGAS_SHP_MACROAREAS.shp") |> 
    st_set_crs("epsg:31983")) |> 
  mapview(zcol = list(NULL, "tipo", "mc_sigla")) |> 
  mapshot(url = "output/mapview/eixos.html")
```


```{r "dados/lotes", cache = TRUE}
IPTU <- read.csv("dados/IPTU/IPTU_2024.csv", sep=";", encoding = "latin1") |>  
    as_tibble() |>  
    select(sql = "NUMERO.DO.CONTRIBUINTE", 
           condominio = "NUMERO.DO.CONDOMINIO",
           area_terreno = "AREA.DO.TERRENO",
           area_construida = "AREA.CONSTRUIDA",
           area_ocupada = "AREA.OCUPADA",
           pavimentos = "QUANTIDADE.DE.PAVIMENTOS",
           ano_construcao = "ANO.DA.CONSTRUCAO.CORRIGIDO",
           tipo = "TIPO.DE.PADRAO.DA.CONSTRUCAO") |>  
    # Separação do número de contribuinte (SQL) em setor quadra e lote
    mutate(setor =  str_sub(sql, 1, 3),
           quadra = str_sub(sql, 4, 6),
           # Quando o lote é um condomínio, haverá vários SQLs no mesmo lote. CD = Condomínio
           lote = str_sub(sql, 7, 10) |>  
             ifelse(condominio == "00-0", yes = _, paste("CD", str_sub(condominio, 1, 2), sep = "")),
           # Tipo de uso
           uso = case_when(str_detect(tipo, "Residencial") ~ "residencial",
                         str_detect(tipo, "Comercial") ~ "comercial",
                         str_detect(tipo, "Oficina") ~ "industrial",
                         str_detect(tipo, "TERRENO") ~ "terreno",
                         str_detect(tipo, "Clube") ~ "entretenimento",
                         .default = "outros")) |> 
  # Agregar por SQL
  group_by(setor, quadra, lote) |>  
  summarize(unidades = n(),
            area_terreno = median(area_terreno), 
            area_construida = sum(area_construida), 
            area_ocupada = median(area_ocupada),
            pavimentos = median(pavimentos),
            ano_construcao = median(ano_construcao),
            uso_predominante = fct_infreq(uso) |> levels() |> first()) |>  
  ungroup() |>  
  mutate(densidade_construtiva = area_construida / area_terreno,
         densidade_habitacional = unidades / area_terreno,
         verticalizacao = area_construida / area_ocupada)

lotes <- list.files(path="dados/lotes/unzip", full.names = FALSE) |>  
  (\(.) paste("dados/lotes/unzip/", ., "/", ., ".shp", sep = ""))() |>  
  lapply(read_sf) |>  
  bind_rows() |>  
  st_set_crs("epsg:31983") |> 
  filter(st_centroid(geometry) |> st_covered_by(eixos.buffersimples) |> as.logical()) |> 
  mutate(lo_lote = ifelse(lo_lote == "0000", paste("CD", lo_condomi, sep = ""), lo_lote),
         lo_lote = ifelse(lo_tp_lote != "F", paste(lo_tp_lote, lo_lote, sep = ""), lo_lote)) |>  
  select(setor = lo_setor, quadra = lo_quadra, lote = lo_lote, tipo_lote = lo_tp_lote)

IPTU.lote <- lotes |>  
  left_join(IPTU, by = join_by(setor, quadra, lote)) |>  
  ungroup()

saveRDS(IPTU.lote, "rdata/IPTU-lote.rds")
saveRDS(lotes, "rdata/lotes.rds")
saveRDS(IPTU, "rdata/IPTU.rds")

remove(IPTU, lotes)
```




```{r "dados/censo", cache = TRUE}
censo2010 <- read_sf("dados/censo/2010/35SEE250GC_SIR.shp") |> 
  filter(CD_GEOCODM == "3550308") |> 
  st_transform("epsg:31983") |> 
  select(id_setor = CD_GEOCODI) |> 
  left_join(readxl::read_excel("dados/censo/2010/Basico_SP1.XLS") |> 
              select(id_setor = Cod_setor, moradores = V002) |> 
              mutate(id_setor = as.character(id_setor)),
            by = join_by(id_setor)) |> 
  filter(st_covered_by(st_centroid(geometry), eixos.buffersimples |> st_buffer(-200)) |> as.logical()) |> 
  mutate(ano = 2010)

censo2022 <- read_sf("dados/censo/2022/SP_Malha_Preliminar_2022.shp") |> 
  filter(CD_MUN == "3550308") |> 
  st_transform("epsg:31983")  |>
  select(id_setor = CD_SETOR, moradores = v0001) |> 
  filter(st_covered_by(st_centroid(geometry), eixos.buffersimples |> st_buffer(-200)) |> as.logical()) |> 
  mutate(ano = 2022)

censo <- bind_rows(list(censo2010, censo2022)) |> 
  mutate(area = st_area(geometry)) 

saveRDS(censo, "rdata/censo.rds")
saveRDS(censo2010, "rdata/censo2010.rds")
saveRDS(censo2022, "rdata/censo2022.rds")

remove(censo2010, censo2022)
```

# Tratamento dos dados

```{r "dados/areas-uso", cache = TRUE}

areas.uso <- censo |> 
  st_intersection(IPTU.lote) |> 
  group_by(id_setor, tipo_lote, uso_predominante, posPDE = ano_construcao > 2014) |> 
  summarize(area = st_union(geometry) |> st_area() |> as.numeric()) |> 
  st_drop_geometry() |> 
  bind_rows(censo |> 
              st_drop_geometry() |> 
              select(id_setor, area) |> 
              mutate(area = as.numeric(area)) |> 
              pivot_longer(area, names_to = "uso_predominante", values_to = "area") |> 
              mutate(uso_predominante = NA)) 

saveRDS(areas.uso, "rdata/areas-uso.rds")

areas.uso |> 
  group_by(tipo_lote, uso_predominante, posPDE) |> 
  summarize(area = sum(area)) |> 
  ungroup() |> 
  mutate(total = "Área do setor\n censitário",
         area = ifelse(is.na(tipo_lote) & is.na(uso_predominante), max(area) - (sum(area) - max(area)), area),
         percent = area / sum(area),
         tipo_lote = case_when(tipo_lote == "F" ~ "Fiscal",
                           tipo_lote == "M" ~ "Espaço Livre",
                           tipo_lote == "V" ~ "Vias de Acesso",
                           TRUE ~ "Não lote"),
         uso_predominante = case_when(uso_predominante == "" ~ "outros",
                           is.na(uso_predominante)~ "outros",
                           TRUE ~ uso_predominante) |> str_to_title(),
         posPDE = case_when(posPDE == TRUE ~ "Pós PDE",
                            posPDE == FALSE ~ "Pré PDE",
                            TRUE ~ NA)) |> 
  group_by(total) |> mutate(total = paste(total, "\n", round(sum(percent) * 100), "%", sep = "")) |> ungroup() |> 
  group_by(tipo_lote) |> mutate(tipo_lote = paste(tipo_lote, "\n", round(sum(percent) * 100, 2), "%", sep = "")) |> ungroup() |> 
  group_by(uso_predominante) |> mutate(uso_predominante = paste(uso_predominante, "\n", round(sum(percent) * 100, 2), "%", sep = "")) |> ungroup() |> 
  group_by(posPDE) |> mutate(posPDE = ifelse(is.na(posPDE), NA, paste(posPDE, "\n", round(sum(percent) * 100, 2), "%", sep = ""))) |> ungroup() |> 
  make_long(total, tipo_lote, uso_predominante, posPDE,value = area) |> 
  mutate(order = ifelse(str_detect(node, "outros|Não lote"), 1, 0)) |> 
  ggplot(aes(x = x, 
             next_x = next_x, 
             node = reorder(node, order), 
             next_node = reorder(next_node, order),
             fill = factor(node),
           value = value,
           label = node)) +
  geom_sankey(flow.alpha = 0.75, na.rm = T) +
  geom_sankey_label(size = 3.5, color = "black", fill = "white", alpha = .9) +
  theme_sankey() +
  scale_fill_viridis_d(option ="G") +
    scale_x_discrete(name = "", position = "top", labels = c("total" = "Setor censitário",
                                                           "tipo_lote" = "Tipo de lote",
                                                           "uso_predominante" = "Qualificação no IPTU",
                                                           "posPDE" = "Ano da construção")) +
  theme(legend.position = "none")

ggsave("output/area_setor.pdf", width = 10, height = 5)

```


```{r "dados/censo-areas", cache = TRUE}
censo.areas <- areas.uso |> 
  mutate(posPDE = ifelse(posPDE, "posPDE", "prePDE"), 
         uso_predominante = case_when(tipo_lote != "F" ~ NA,
                                      uso_predominante == "residencial" ~ "residencial",
                                      TRUE ~ "outros")) |> 
  drop_na() |> 
  group_by(id_setor, uso_predominante, posPDE) |> 
  summarize(area = sum(area)) |>   
  group_by(id_setor) |> 
  mutate(area_lote = sum(area)) |> 
  filter(uso_predominante == "residencial") |> 
  mutate(area_residencial = sum(area)) |> 
  pivot_wider(id_cols = c(id_setor, area_lote, area_residencial), names_from = posPDE, values_from = area, names_prefix = "area_residencial_") |> 
  mutate(across(c(area_residencial_posPDE, area_residencial_prePDE), ~ replace_na(.x, 0))) |> 
  right_join(censo) |> 
  mutate(area = as.numeric(area),
         area_residencial = area_residencial / area_lote,
         area_residencial_novo_percent = area_residencial_posPDE / area_lote,
         area_lote = area_lote / area) |> 
  left_join(censo |> 
              st_set_geometry("geometry") |> 
              st_intersection(eixos |> st_union()) |> 
              mutate(area_eixo = as.numeric(st_area(geometry))) |> 
              st_drop_geometry() |> 
              select(id_setor, area_eixo_total = area_eixo)) |> 
  mutate(area_eixo = replace_na(area_eixo_total, 0) / (area),
         area_eixo_lote = replace_na(area_eixo_total, 0) / (area * area_lote)) |> 
  select(id_setor, ano, moradores, area, area_lote, area_residencial, area_residencial_novo_percent, area_eixo, area_eixo_lote, geometry)

saveRDS(censo.areas, "rdata/censo-areas.rds")
```


```{r "dados/censo-distancias", cache = TRUE}
censo.distancias <- censo.areas |> 
  mutate(centroid = st_centroid(geometry),
         posicao_centroide = ifelse(centroid |> 
                                      st_intersects(eixos.miolo |> st_union()) |> 
                                      as.logical() |> 
                                      replace_na(0), 
                                    "eixo", "fora"),
         distancia = as.numeric(st_distance(centroid, eixos.contorno)[,1]))


saveRDS(censo.distancias, "rdata/censo-distancias.rds")

censo.distancias |>
  st_drop_geometry() |>
  ggplot(aes(x = posicao_centroide, y = area_eixo_lote)) +
  annotate("rect", xmin = 1.5, xmax = 2.5, ymin = .0, ymax = .05, fill = "darkred", alpha = .1) +
  annotate("rect", xmin = .5, xmax = 1.5, ymin = .9, ymax = 1, fill = "darkgreen", alpha = .1) +
  geom_hline(yintercept = .90, linetype = "dotted") +
  geom_hline(yintercept = .05, linetype = "dotted") +
  geom_violin(lwd = 0.25, stroke = 0) +
  facet_wrap(~ano) +
  theme_bw() +
  scale_y_continuous(labels = scales::percent, limits = c(0,1)) +
  labs(x = "Região mais próxima ao centroide", y = "Percentual da área em eixo")

ggsave("output/percent-eixo.pdf", width = 7, height = 5)
```

```{r "dados/IPTU-distancias", cache = TRUE}
IPTU.distancias <- IPTU.lote |>
  mutate(
    centroid = st_centroid(geometry),
    posicao_centroide = ifelse(
      centroid |>
        st_intersects(eixos.miolo |> st_union()) |>
        as.logical() |>
        replace_na(0),
      "eixo",
      "fora"
    ),
    distancia = as.numeric(st_distance(centroid, eixos.contorno)[,1])) |> 
    st_drop_geometry()


saveRDS(IPTU.distancias, "rdata/IPTU-distancias.rds")
```



```{r}
df.IPTU <- IPTU.distancias |> 
  # filter(tipo_lote == "F", ano_construcao >= 2002, ano_construcao <= 2022) |> 
  mutate(posPDE = ano_construcao > 2014,
         residencial = uso_predominante == "residencial",
         grupo = case_when(posicao_centroide == "eixo" ~ "tratamento",
                           posicao_centroide == "fora" ~ "controle",
                           TRUE ~ "descartado"),
         distancia = case_when(grupo == "controle" ~ -distancia,
                               grupo == "tratamento" ~ distancia,
                               TRUE ~ NA)) |> 
  select(setor, quadra, lote, 
         distancia, grupo, 
         pavimentos, densidade_construtiva, densidade_habitacional, 
         ano_construcao, posPDE, uso_predominante, posPDE) 


df.censo <- censo.distancias |>
  mutate(grupo = case_when(posicao_centroide == "eixo" & area_eixo_lote > .9 ~ "tratamento",
                           posicao_centroide == "fora" & area_eixo_lote < .05 ~ "controle",
                           TRUE ~ "descartado")) |> 
  mutate(densidade = moradores / area,
         densidade_lote = moradores / (area * area_lote),
         densidade_residencial = moradores / (area * area_lote * area_residencial)) |> 
  select(id_setor, ano, grupo, starts_with("densidade"), area_residencial_novo_percent)


distrito <- read_sf("dados/distrito/SIRGAS_SHP_distrito.shp") |> 
  filter(ds_nome == "VILA MARIANA") |> 
  select()

gg <- ggplot() +
  # geom_sf(data = df.censo |>
  #           filter(ano == 2022) |>
  #           right_join(censo |> select(id_setor) |> st_crop(distrito)),
  #         aes(geometry = geometry, fill = grupo),
  #         color = NA) +
  # geom_sf(data = censo |> filter(ano == 2022) |> st_crop(distrito), fill = NA, colour = "#313638", alpha = .3) +
  geom_sf(data = df.IPTU |> 
            right_join(IPTU.lote |> select(setor, quadra, lote) |> st_crop(distrito)) |> 
            mutate(cor = case_when(grupo == "tratamento" & uso_predominante == "residencial" & posPDE == TRUE  ~ "tratamento residencial novo",
                                   grupo == "tratamento" & uso_predominante == "residencial" & posPDE == FALSE ~ "tratamento residencial antigo",
                                   grupo == "tratamento" & uso_predominante != "residencial"                   ~ "tratamento não residencial",
                                   grupo == "controle" & uso_predominante == "residencial" & posPDE == TRUE    ~ "controle residencial novo",
                                   grupo == "controle" & uso_predominante == "residencial" & posPDE == FALSE   ~ "controle residencial antigo",
                                   grupo == "controle" & uso_predominante != "residencial"                     ~ "controle não residencial",
                                   TRUE ~ "outros")),
          aes(geometry = geometry, fill = cor),
          lwd = .1, stroke = 0) + 
  theme_void() +
  # scale_fill_brewer() +
  # scale_fill_manual(name = "Controle", labels = c""
  #   values = c("outros" = "white",
  #              "tratamento residencial novo"  = "#1BB6AFFF",
  #              "tratamento residencial antigo"= "#0076BBFF",
  #              "tratamento não residencial"   = "#172869FF",
  #              "controle residencial novo"    = "#FF3200FF",
  #                              "controle residencial antigo"  = "#E9A17CFF",
  #                              "controle não residencial"     = "#E9E4A6FF")) +
   scale_fill_manual(values = c("outros" = "white",
                               "tratamento residencial novo"  = "#1BB6AFFF",
                               "tratamento residencial antigo"= "#0076BBFF",
                               "tratamento não residencial"   = "#172869FF",
                               "controle residencial novo"    = "#FF3200FF",
                               "controle residencial antigo"  = "#E9A17CFF",
                               "controle não residencial"     = "#E9E4A6FF")) +
  theme(legend.position = "inside",
        legend.position.inside = c(.85, .8))


ggsave("output/mapa-censo.pdf", height = 10, width = 10)

```






